name: Split Packages
on:
  push:
    branches:
      - main
      - '0.*'
    tags:
      - '*'
jobs:
  tag_split_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [
          'package-a',
          'package-b'
        ]
    steps:

      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
      - name: Split ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'alecritson'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_REF#refs/heads/}

      - name: Set env
        if: "startsWith(github.ref, 'refs/tags/')"
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: "Echo thingy"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: echo "${GITHUB_TAG%.*}"

      - name: Tag ${{ matrix.package }}
        if: "startsWith(github.ref, 'refs/tags/')"
        run: echo "${GITHUB_REF#refs/tags/}"
        #uses: symplify/github-action-monorepo-split@main
        #env:
          #GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        #with:
          #tag: ${GITHUB_REF#refs/tags/}
          #package_directory: 'packages/${{ matrix.package }}'
          #repository_organization: 'alecritson'
          #repository_name: '${{ matrix.package }}'
          #user_name: "GitHub Action"
          #user_email: "action@github.com"
          #branch: ${${GITHUB_REF#refs/tags/}%.*}
